"""Telescoping vs leave-one-out attribution comparison.

PRISM's per-column contribution ``Delta_i = g_i - g_{i-1}`` is an
*ordered, realized* decomposition of the total fidelity loss along the
circuit.  An alternative *interventional* estimand is leave-one-out
(LOO) ablation: switch noise off at column ``i`` only and measure how
much total loss disappears,

    LOO_i = g_L(all columns noisy) - g_L(all except i noisy).

This script computes both estimands on two suite circuits under the
suite's depolarizing channel and reports their per-column agreement.

Outputs (under :file:`paper/summary/`):

* ``loo_comparison.csv``  -- one row per (circuit, column)
* ``loo_comparison.json`` -- per-circuit correlation summary
* ``loo_comparison.md``   -- Markdown table
* ``loo_comparison.tex``  -- LaTeX ``tabular`` body

Run with::

    python scripts/loo_comparison.py
"""

from __future__ import annotations

import csv
import json
import sys
import time
from pathlib import Path

import numpy as np

_PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_PROJECT_ROOT))

from PRISM.engine.circuit import QuantumCircuit    # noqa: E402
from PRISM.engine.debugger import CircuitDebugger  # noqa: E402
from PRISM.engine.noise import NoiseModel          # noqa: E402
from PRISM.replay import ReplayConfig              # noqa: E402

N_TRIALS = 2000  # higher than the suite default: LOO differences are
                 # differences of two Monte Carlo means, so they need a
                 # tighter budget than the telescoping estimand.
SEED = 630000

PAIRS = [
    ("attr_ghz4_depolarizing", "GHZ-4 + Depol"),
    ("attr_qaoa_maxcut_depolarizing", "QAOA($C_4$) + Depol"),
]


def total_loss(debugger, circuit, noise, noise_columns, seed):
    attr = debugger.compute_noise_attribution(
        circuit, noise, n_trials=N_TRIALS, seed=seed,
        noise_columns=noise_columns,
    )
    return float(sum(attr.delta_fidelity)), attr


def main() -> None:
    experiments = _PROJECT_ROOT / "paper" / "experiments"
    summary_dir = _PROJECT_ROOT / "paper" / "summary"
    summary_dir.mkdir(parents=True, exist_ok=True)

    debugger = CircuitDebugger()
    rows = []
    summary = {}

    t0 = time.perf_counter()
    for stem, label in PAIRS:
        cfg = ReplayConfig.load(experiments / f"{stem}.json")
        circuit = QuantumCircuit.from_dict(cfg.circuit)
        noise = NoiseModel.from_dict(cfg.noise_model)
        n_cols = len(circuit.compute_layers())

        g_full, attr_full = total_loss(
            debugger, circuit, noise, None, SEED)
        telescoping = np.asarray(attr_full.delta_fidelity)

        loo = np.zeros(n_cols)
        for i in range(n_cols):
            active = set(range(n_cols)) - {i}
            g_minus_i, _ = total_loss(
                debugger, circuit, noise, active, SEED + 1 + i)
            loo[i] = g_full - g_minus_i

        corr = float(np.corrcoef(telescoping, loo)[0, 1])
        summary[stem] = {
            "label": label,
            "n_columns": n_cols,
            "g_full": g_full,
            "pearson_r": corr,
            "sum_telescoping": float(telescoping.sum()),
            "sum_loo": float(loo.sum()),
        }
        for i in range(n_cols):
            rows.append({
                "circuit": label, "column": i,
                "telescoping_delta": round(float(telescoping[i]), 6),
                "loo_delta": round(float(loo[i]), 6),
            })
        print(f"{label:22s} r = {corr:.3f}  "
              f"(sum tel {telescoping.sum():.3f} vs "
              f"sum LOO {loo.sum():.3f}, g_L {g_full:.3f})")
    elapsed = time.perf_counter() - t0

    with open(summary_dir / "loo_comparison.csv", "w", newline="") as fh:
        writer = csv.DictWriter(fh, fieldnames=list(rows[0].keys()),
                                lineterminator="\n")
        writer.writeheader()
        writer.writerows(rows)

    with open(summary_dir / "loo_comparison.json", "w") as fh:
        json.dump({"n_trials": N_TRIALS, "seed": SEED,
                   "pairs": summary,
                   "elapsed_seconds": round(elapsed, 1)}, fh, indent=2)

    with open(summary_dir / "loo_comparison.md", "w") as fh:
        fh.write("| Circuit | col | telescoping Delta_i | LOO_i |\n")
        fh.write("|---|---:|---:|---:|\n")
        for r in rows:
            fh.write(f"| {r['circuit']} | {r['column']} "
                     f"| {r['telescoping_delta']:.4f} "
                     f"| {r['loo_delta']:.4f} |\n")

    with open(summary_dir / "loo_comparison.tex", "w") as fh:
        fh.write("% Auto-generated by scripts/loo_comparison.py\n")
        fh.write("\\begin{tabular}{@{}lrrr}\n\\br\n")
        fh.write("Circuit & col & telescoping $\\overline{\\Delta}_i$ "
                 "& $\\mathrm{LOO}_i$ \\\\\n\\mr\n")
        for r in rows:
            fh.write(f"{r['circuit']} & {r['column']} & "
                     f"{r['telescoping_delta']:.4f} & "
                     f"{r['loo_delta']:.4f} \\\\\n")
        fh.write("\\br\n\\end{tabular}\n")

    print(f"done in {elapsed:.0f}s; wrote paper/summary/loo_comparison.*")


if __name__ == "__main__":
    main()
